debian/tmp/usr/share/doc/libtelepathy-glib-doc/telepathy-glib
# Many of the examples are in subdirectories, which dh_installexamples
# can't do (without copying the whole directory, which we don't want either)
# so we do them here.
examples/client/*.c /usr/share/doc/libtelepathy-glib-doc/examples/client
examples/client/*.am /usr/share/doc/libtelepathy-glib-doc/examples/client
examples/extensions/*.xml /usr/share/doc/libtelepathy-glib-doc/examples/extensions
examples/extensions/*.c /usr/share/doc/libtelepathy-glib-doc/examples/extensions
examples/extensions/*.h /usr/share/doc/libtelepathy-glib-doc/examples/extensions
examples/extensions/*.am /usr/share/doc/libtelepathy-glib-doc/examples/extensions
examples/cm/*.am /usr/share/doc/libtelepathy-glib-doc/examples/cm
examples/cm/echo/*.am /usr/share/doc/libtelepathy-glib-doc/examples/cm/echo
examples/cm/echo/*.c /usr/share/doc/libtelepathy-glib-doc/examples/cm/echo
examples/cm/echo/*.h /usr/share/doc/libtelepathy-glib-doc/examples/cm/echo
examples/cm/extended/*.am /usr/share/doc/libtelepathy-glib-doc/examples/cm/extended
examples/cm/extended/*.c /usr/share/doc/libtelepathy-glib-doc/examples/cm/extended
examples/cm/extended/*.h /usr/share/doc/libtelepathy-glib-doc/examples/cm/extended
examples/cm/no-protocols/*.am /usr/share/doc/libtelepathy-glib-doc/examples/cm/no-protocols
examples/cm/no-protocols/*.c /usr/share/doc/libtelepathy-glib-doc/examples/cm/no-protocols
examples/cm/no-protocols/*.h /usr/share/doc/libtelepathy-glib-doc/examples/cm/no-protocols
examples/cm/no-protocols/Makefile.am /usr/share/doc/libtelepathy-glib-doc/examples/cm/no-protocols
